# build settings for frontend vite app
[build]
  base    = "frontend"
  command = "npm run build"
  publish = "dist"

# settings for backend node.js functions
[functions]
  directory = "backend"

# rewrite rule to let frontend talk to backend
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200