-- Migration: Add new fields to Habitat table
-- Date: 2024

ALTER TABLE Habitat ADD COLUMN IF NOT EXISTS imageUrl VARCHAR(200) DEFAULT NULL;
ALTER TABLE Habitat ADD COLUMN IF NOT EXISTS extraDetails VARCHAR(1000) DEFAULT NULL;
ALTER TABLE Habitat ADD COLUMN IF NOT EXISTS climate VARCHAR(500) DEFAULT NULL;
ALTER TABLE Habitat ADD COLUMN IF NOT EXISTS funFact VARCHAR(500) DEFAULT NULL;

